# Generated by Django 4.1.2 on 2022-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='milage',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='no_of_owners',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='vin_no',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='features',
            field=models.CharField(choices=[('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=255),
        ),
    ]
