# Generated by Django 4.1.2 on 2022-11-14 11:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_created_date_carmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(max_length=255),
        ),
    ]
