# Generated by Django 4.1.2 on 2022-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_description_alter_carmodel_fuel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='miles',
            new_name='km',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='features',
            field=models.CharField(choices=[('Tanirovka', 'Tanirovka'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Malibu Bar', 'Malibu Bar'), ('Airbag', 'Airbag'), ('Power Steering', 'Power Steering'), ('Avtoregistartr', 'Avtoregistratr'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Planshet ekran', 'Planshen ekran')], max_length=255),
        ),
    ]
