# Generated by Django 4.1.2 on 2022-11-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_miles_carmodel_km_carmodel_transmission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
    ]
